name: Deploy Environment

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
  aws_region: ${{ vars.AWS_REGION }}
  aws_role: ${{ vars.AWS_ROLE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.aws_region }}
            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
            role-session-name: GitHubActions
  
      - uses: extractions/setup-just@v1

      - name: build
        shell: bash
        run: just deploy

      - name: set-envs
        shell: bash
        run: |
          cd tf

          S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME"
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV

          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TEST_FILE_NAME=$TIMESTAMP-test.txt
          echo "TEST_FILE_NAME=$TEST_FILE_NAME"
          echo "TEST_FILE_NAME=$TEST_FILE_NAME" >> $GITHUB_ENV

      - name: test s3 upload
        shell: bash
        run: |
            echo "badgers" > $GITHUB_WORKSPACE/$TEST_FILE_NAME
            aws s3 cp $GITHUB_WORKSPACE/$TEST_FILE_NAME s3://$S3_BUCKET_NAME/input/$TEST_FILE_NAME
            sleep 2

      - name: test confirm processed
        shell: bash
        run: |
            aws s3api head-object --bucket $S3_BUCKET_NAME --key "processed/$TEST_FILE_NAME"
